# ""[TOKEN 8] : dev.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.dev""

### SIGNUP
POST http://localhost:3000/api/signup
Content-Type: application/json

{
  "name": "Muhamad Farhan", 
  "email": "muhamadfarhan.inc@gmail.com", 
  "password": "@MonkeyDDragon1"
}


### SINGIN
POST http://localhost:3000/api/signin
Content-Type: application/json

{
    "email": "muhamadfarhan.inc@gmail.com",
    "password": "@MonkeyDDragon1"
}

### Get News Articles
GET http://localhost:3000/api/news
Content-Type: application/json

### Get News Articles by title
GET http://localhost:3000/api/news?title=bosbos-teknologi-klaim-hp-bakal-segera-punah-ini-penggantinya
Content-Type: application/json

### Get News Articles by category
GET http://localhost:3000/api/news?category=Bisnis
Content-Type: application/json

### Get News Articles by status
GET http://localhost:3000/api/news?status=pending
Content-Type: application/json

### Get News Articles by limit
GET http://localhost:3000/api/news?limit=1
Content-Type: application/json

### Get News Articles by skip
GET http://localhost:3000/api/news?skip=5
Content-Type: application/json

### Get News Articles by authorId
GET http://localhost:3000/api/news?authorId=67187a9209bd0c0b5a1ae078
Content-Type: application/json

### Get News Articles by district
GET http://localhost:3000/api/news?district=Cicalengka+Wetan
Content-Type: application/json

### Get News Articles by regency
GET http://localhost:3000/api/news?regency=Bandung
Content-Type: application/json

### Search News Articles by title
GET http://localhost:3000/api/news/search?title=Bos

### Update Status News Single
PATCH http://localhost:3000/api/news/status
Authorization: Bearer dev.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.dev
Content-Type: application/json

{
  "newsId": "6726285f3a39bcb90c123e79",
  "status": "pending"
}

### Update Status News Many
PATCH http://localhost:3000/api/news/status
Authorization: Bearer dev.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.dev
Content-Type: application/json

{
  "newsId": [
    "6726285f3a39bcb90c123e79",
    "672628673a39bcb90c123e7d",
    "6726286b3a39bcb90c123e81",
    "6726286c3a39bcb90c123e85",
    "6726286e3a39bcb90c123e89",
    "672628703a39bcb90c123e8d",
    "672628723a39bcb90c123e91"
  ],
  "status": "approved"
}

### Delete News All
DELETE http://localhost:3000/api/news
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MTg3YTkyMDliZDBjMGI1YTFhZTA3OCIsImVtYWlsIjoibXVoYW1hZGZhcmhhbi5pbmNAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzMwMDg0NzAyLCJleHAiOjE3MzAwODgzMDJ9.mf312hcBxTRbUPnyu3lVjIk7UoWubXr_09aKVcSXMwE
Content-Type: application/json

### Delete News By Id
DELETE http://localhost:3000/api/news?id=671eef5860b7c6fb17da14a4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MTg3YTkyMDliZDBjMGI1YTFhZTA3OCIsImVtYWlsIjoibXVoYW1hZGZhcmhhbi5pbmNAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzMwMDg0NzAyLCJleHAiOjE3MzAwODgzMDJ9.mf312hcBxTRbUPnyu3lVjIk7UoWubXr_09aKVcSXMwE
Content-Type: application/json

### Get authors by id
GET http://localhost:3000/api/authors?id=6726277c3a39bcb90c123e6f
Content-Type: application/json














### ADMIN ACCESS ###

### Update Role Account
PATCH http://localhost:3000/api/admin
Authorization: Bearer dev.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.dev

{
  "userId": "6726277c3a39bcb90c123e6f",
  "role": "admin"
}

### Get data Account
GET http://localhost:3000/api/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY3MjYyNzdjM2EzOWJjYjkwYzEyM2U2ZiIsInJvbGUiOiJhZG1pbiIsIm5hbWUiOiJNdWhhbWFkIEZhcmhhbiIsImltYWdlIjoidXNlci5wbmciLCJpYXQiOjE3MzA3MzA5ODUsImV4cCI6MTczMDczNDU4NX0.IxDS16ZScQIrIPEBRfh6IVLdikHiZLwaq5jYEcrBPog
Content-Type: application/json

### GET LOCATION WITH OPENCAGE
GET https://api.opencagedata.com/geocode/v1/json?q=-6.9986312+107.8308232&key=b7fced23e74544808f1afd64165ca1a8
Content-Type: application/json

### DELETE COLLECTION
DELETE http://localhost:3000/api/admin/mongodb
Authorization: Bearer dev.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.dev
Content-Type: application/json

{
  "name": "users"
}

###
GET https://bisnis.tempo.co/read/1934843/bri-dukung-rencana-prabowo-putihkan-utang-petani-dan-nelayan-sudah-ditunggu-tunggu