import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const expletusSans = localFont({
  src: "./fonts/ExpletusSans.ttf",
  variable: "--font-expletus-sans",
  weight: "400 500 600 700",
});

export const metadata: Metadata = {
  title: "Portal Berita Lokal Indonesia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta
        name="google-site-verification"
        content="g1K9uwCjFYm6Emspt7Ch4BHgj7FLBnqOW-770w8_uP8"
      />
      <body
        className={`${expletusSans.variable} antialiased overflow-x-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
